#!/bin/bash
# ─────────────────────────────────────────────────────────────
# Lucid-3D AI Driver — Phase 1b
#
# Picks the next ready issue, launches Claude Code to implement it,
# runs tests, and creates a PR if all pass.
#
# Usage:
#   ./scripts/ai-driver.sh           # Process next ready issue
#   ./scripts/ai-driver.sh --dry-run # Show what would be done
#   ./scripts/ai-driver.sh --issue 1 # Process specific issue
# ─────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."

DRY_RUN=false
SPECIFIC_ISSUE=""
MAX_RETRIES=3
REPO="MoonKing123/lucid-3d"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    --issue)   SPECIFIC_ISSUE="$2"; shift 2 ;;
    *)         echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# ── Pick next issue ──────────────────────────────────────────

if [[ -n "$SPECIFIC_ISSUE" ]]; then
  ISSUE_NUM="$SPECIFIC_ISSUE"
else
  ISSUE_NUM=$(GITHUB_TOKEN="" gh issue list --repo "$REPO" --label "ready,ai-task" --state open --json number --jq '.[0].number // empty' 2>/dev/null)
fi

if [[ -z "$ISSUE_NUM" ]]; then
  echo "No ready issues found. Done!"
  exit 0
fi

# Get issue details
ISSUE_TITLE=$(GITHUB_TOKEN="" gh issue view "$ISSUE_NUM" --repo "$REPO" --json title --jq '.title')
ISSUE_BODY=$(GITHUB_TOKEN="" gh issue view "$ISSUE_NUM" --repo "$REPO" --json body --jq '.body')

echo "════════════════════════════════════════════════"
echo "  Issue #${ISSUE_NUM}: ${ISSUE_TITLE}"
echo "════════════════════════════════════════════════"

if $DRY_RUN; then
  echo "[dry-run] Would process issue #${ISSUE_NUM}"
  echo "$ISSUE_BODY" | head -20
  exit 0
fi

# ── Create branch ────────────────────────────────────────────

BRANCH="feat/issue-${ISSUE_NUM}"
git checkout main
git pull origin main 2>/dev/null || true
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# ── Build AI prompt ──────────────────────────────────────────

PROMPT="You are working on the lucid-3d project — an AI-native 3D game engine.

## Your task
Implement GitHub Issue #${ISSUE_NUM}: ${ISSUE_TITLE}

## Issue spec
${ISSUE_BODY}

## Rules
1. Read CLAUDE.md first for project conventions.
2. Create ONLY the files specified in the issue.
3. Run \`pnpm run test\` to verify your implementation passes all pre-written tests.
4. Run \`pnpm run test:visual\` to verify no visual regressions.
5. If tests fail, read the error and fix your code. Do NOT modify test files.
6. When all tests pass, stop.

## Important
- Do NOT modify any files in test/ directory.
- Do NOT add new dependencies.
- Use pure functions where specified.
- Float32Array for Vec3 (length 3) and Mat4 (length 16).
- Column-major layout for Mat4 (WebGL convention).
"

# ── Launch Claude Code ───────────────────────────────────────

echo ""
echo "Launching Claude Code agent..."
echo ""

for attempt in $(seq 1 $MAX_RETRIES); do
  echo "── Attempt ${attempt}/${MAX_RETRIES} ──"

  # Run Claude Code with the prompt
  echo "$PROMPT" | claude --print 2>&1 | tee "/tmp/lucid-3d-agent-${ISSUE_NUM}-${attempt}.log"

  # Run tests
  echo ""
  echo "Running tests..."
  if pnpm run test 2>&1; then
    echo "✅ Unit tests passed!"

    # Check if dev server is needed for visual tests
    if pnpm run test:visual 2>&1; then
      echo "✅ Visual tests passed!"
      echo ""
      echo "All tests pass on attempt ${attempt}!"
      break
    else
      echo "❌ Visual tests failed on attempt ${attempt}"
      if [[ $attempt -eq $MAX_RETRIES ]]; then
        echo "Max retries reached. Aborting."
        GITHUB_TOKEN="" gh issue comment "$ISSUE_NUM" --repo "$REPO" \
          --body "❌ AI agent failed after ${MAX_RETRIES} attempts. Visual tests did not pass. Manual intervention needed."
        exit 1
      fi
    fi
  else
    echo "❌ Unit tests failed on attempt ${attempt}"
    if [[ $attempt -eq $MAX_RETRIES ]]; then
      echo "Max retries reached. Aborting."
      GITHUB_TOKEN="" gh issue comment "$ISSUE_NUM" --repo "$REPO" \
        --body "❌ AI agent failed after ${MAX_RETRIES} attempts. Unit tests did not pass. Manual intervention needed."
      exit 1
    fi
  fi
done

# ── Commit and PR ────────────────────────────────────────────

git add -A
git commit -m "$(cat <<EOF
feat: implement #${ISSUE_NUM} — ${ISSUE_TITLE}

Implemented by AI agent (Claude Code).
All pre-written tests pass.

Fixes #${ISSUE_NUM}

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>
EOF
)"

GITHUB_TOKEN="" git push -u origin "$BRANCH" 2>&1

GITHUB_TOKEN="" gh pr create --repo "$REPO" \
  --title "feat: #${ISSUE_NUM} — ${ISSUE_TITLE}" \
  --body "$(cat <<EOF
## Summary
AI-implemented solution for #${ISSUE_NUM}.

## Test results
- ✅ Unit tests pass
- ✅ Visual regression tests pass
- ✅ No regressions

Fixes #${ISSUE_NUM}

🤖 Generated by AI Driver (Phase 1b)
EOF
)" 2>&1

echo ""
echo "════════════════════════════════════════════════"
echo "  ✅ Issue #${ISSUE_NUM} completed!"
echo "════════════════════════════════════════════════"

# ── Mark issue as done (after PR merge) ──────────────────────
# Note: PR merge will auto-close the issue via "Fixes #N"

# ── Check if #5 (renderer) should be unblocked ──────────────
OPEN_DEPS=$(GITHUB_TOKEN="" gh issue list --repo "$REPO" --label "ready" --state open --json number --jq 'length')
if [[ "$OPEN_DEPS" -eq 0 ]]; then
  echo "All ready issues closed. Adding 'ready' label to #5 (renderer)."
  GITHUB_TOKEN="" gh issue edit 5 --repo "$REPO" --add-label "ready" 2>/dev/null || true
fi
