#!/usr/bin/env node
/**
 * Pre-flight check: ensure all test imports have corresponding src files.
 * If a src module doesn't exist, create a stub with __STUB__ = true.
 * If a test file imports a stub but doesn't have auto-skip logic, patch it.
 *
 * Run: node scripts/ensure-stubs.mjs [--fix]
 *   --fix: auto-create stubs and patch tests (default in CI)
 *   no flag: dry-run, report issues only
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname, relative } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const FIX = process.argv.includes('--fix');

// Find all test files
const testFiles = execSync('find test/unit -name "*.test.ts"', { cwd: ROOT, encoding: 'utf-8' })
  .trim().split('\n').filter(Boolean);

let issues = 0;
let fixed = 0;

for (const testFile of testFiles) {
  const fullTestPath = resolve(ROOT, testFile);
  const content = readFileSync(fullTestPath, 'utf-8');

  // Extract all relative src imports (patterns like ../../src/ or ../../../src/)
  const importRegex = /from\s+['"]((?:\.\.\/)+src\/.+?)['"]/g;
  let match;

  while ((match = importRegex.exec(content)) !== null) {
    const importPath = match[1];

    // Apply the same alias as vitest.config.ts: ../../src/X → ROOT/src/X
    const srcRelative = importPath.replace(/^(?:\.\.\/)+src\//, 'src/');
    let srcPath = resolve(ROOT, srcRelative);
    if (!srcPath.endsWith('.ts')) srcPath += '.ts';

    const relSrc = srcRelative.endsWith('.ts') ? srcRelative : srcRelative + '.ts';

    if (!existsSync(srcPath)) {
      issues++;
      console.log(`[MISSING] ${testFile} imports ${relSrc}`);

      if (FIX) {
        // Create stub
        mkdirSync(dirname(srcPath), { recursive: true });

        // Parse exports needed from the test file
        const exports = extractExpectedExports(content, importPath);

        const stub = generateStub(relSrc, testFile, exports);
        writeFileSync(srcPath, stub);
        console.log(`  [FIXED] Created stub: ${relSrc}`);
        fixed++;
      }
    } else {
      // Check if src file is a stub and test has auto-skip
      const srcContent = readFileSync(srcPath, 'utf-8');
      if (srcContent.includes('__STUB__') && !content.includes('__STUB__') && !content.includes('describeImpl')) {
        issues++;
        console.log(`[NO-SKIP] ${testFile} imports stub ${relSrc} but has no auto-skip logic`);

        if (FIX) {
          const patched = patchTestWithAutoSkip(content, importPath);
          if (patched !== content) {
            writeFileSync(fullTestPath, patched);
            console.log(`  [FIXED] Patched auto-skip into ${testFile}`);
            fixed++;
          }
        }
      }
    }
  }
}

// Summary
console.log(`\n=== Stub Check: ${issues} issues found, ${fixed} fixed ===`);
if (issues > 0 && !FIX) {
  console.log('Run with --fix to auto-create stubs and patch tests.');
  process.exit(1);
}
process.exit(0);

// ── Helpers ─────────────────────────────────────────────────────

function extractExpectedExports(testContent, importPath) {
  // Find the import statement for this path and extract named exports
  const escaped = importPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`import\\s*\\{([^}]+)\\}\\s*from\\s*['"]${escaped}['"]`);
  const m = testContent.match(re);
  if (!m) return [];
  return m[1].split(',')
    .map(s => s.trim())
    .filter(s => s && !s.startsWith('type '));
}

function generateStub(relSrc, testFile, exports) {
  const lines = [
    '/**',
    ` * STUB — ${relSrc} (not yet implemented).`,
    ` * Auto-generated by ensure-stubs.mjs.`,
    ` * @see ${testFile}`,
    ' */',
    '',
    'export const __STUB__ = true;',
    '',
  ];

  for (const exp of exports) {
    // Heuristic: PascalCase = class, camelCase = function
    if (/^[A-Z]/.test(exp)) {
      lines.push(`export class ${exp} {`);
      lines.push(`  constructor(..._args: any[]) {}`);
      lines.push(`}`);
    } else {
      lines.push(`export function ${exp}(..._args: any[]): any {`);
      lines.push(`  throw new Error('Not implemented — stub');`);
      lines.push(`}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function patchTestWithAutoSkip(content, importPath) {
  // Already has auto-skip?
  if (content.includes('describeImpl') || content.includes('__STUB__')) return content;

  // Find the import line for the stub module
  const escaped = importPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const importRe = new RegExp(`(import\\s*\\{[^}]+\\}\\s*from\\s*['"]${escaped}['"];?)`);
  const importMatch = content.match(importRe);
  if (!importMatch) return content;

  // Replace named import with namespace import + destructure
  const namedImportRe = new RegExp(`import\\s*\\{([^}]+)\\}\\s*from\\s*['"]${escaped}['"]`);
  const namedMatch = content.match(namedImportRe);
  if (!namedMatch) return content;

  const names = namedMatch[1].split(',').map(s => s.trim()).filter(Boolean);
  const typeNames = names.filter(n => n.startsWith('type '));
  const valueNames = names.filter(n => !n.startsWith('type '));

  const moduleName = '_mod_' + importPath.split('/').pop().replace(/[^a-zA-Z]/g, '');

  let replacement = `import * as ${moduleName} from '${importPath}';\n`;
  if (typeNames.length > 0) {
    replacement += `import { ${typeNames.join(', ')} } from '${importPath}';\n`;
  }
  replacement += `\n// Auto-skip if module is still a stub\n`;
  replacement += `const _isStub = '__STUB__' in ${moduleName} && (${moduleName} as any).__STUB__ === true;\n`;
  replacement += `const describeImpl = _isStub ? describe.skip : describe;\n`;
  if (valueNames.length > 0) {
    replacement += `const { ${valueNames.join(', ')} } = ${moduleName};\n`;
  }

  let patched = content.replace(importRe, replacement);

  // Replace top-level describe( with describeImpl(
  patched = patched.replace(/^describe\(/gm, 'describeImpl(');

  return patched;
}
