/**
 * scripts/post-issue-evidence.ts
 * Issue 评论上传器：把截图打包成 markdown 评论，发布到指定 GitHub Issue。
 *
 * 用法：
 *   tsx scripts/post-issue-evidence.ts --issue <n> --phase <n> --kr <name> --images <glob> [options]
 *
 * 注意：gh CLI 使用 keyring 凭证，若环境变量 GITHUB_TOKEN 有残留过期值会导致 401。
 *       本脚本启动时自动 unset，或手动执行 `unset GITHUB_TOKEN`。
 */

import * as fsNode from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';

// 清除可能过期的环境变量，让 gh 使用 keyring 凭证
delete process.env['GITHUB_TOKEN'];

// ─────────────────────────────────────────────
// 公开类型与接口
// ─────────────────────────────────────────────

export interface ImageEntry {
  moment: string;
  url: string;
}

export interface GlobFS {
  glob(pattern: string): string[];
}

export interface GenerateMarkdownOptions {
  phase: number;
  kr: string;
  demo: string;
  images: ImageEntry[];
  date?: string;
}

// ─────────────────────────────────────────────
// 可测试的工具函数（由测试文件直接导入）
// ─────────────────────────────────────────────

/**
 * 从回归路径中提取 demo 名称。
 * 期望格式：docs/regression/phase-{N}/{demo}/{file}
 */
export function inferDemoFromPath(filePath: string): string {
  const match = filePath.match(/docs\/regression\/phase-\d+\/([^/]+)\//);
  return match ? match[1] : 'unknown';
}

/**
 * 生成 GitHub raw 文件 URL（依赖图片已 commit 进 main）。
 */
export function buildRawUrl(filePath: string, repo: string): string {
  return `https://raw.githubusercontent.com/${repo}/main/${filePath}`;
}

/**
 * 生成 Issue 评论 markdown。
 */
export function generateMarkdown(opts: GenerateMarkdownOptions): string {
  const date = opts.date ?? new Date().toISOString().split('T')[0];
  const tableRows = opts.images
    .map(img => `| ${img.moment}   | ![${img.moment}](${img.url}) |`)
    .join('\n');

  const tableSection =
    opts.images.length > 0
      ? `截图证据：\n\n| 时刻 | 截图 |\n|------|------|\n${tableRows}\n`
      : `截图证据：\n\n（无截图）\n`;

  return `✅ Regression Verified ${date}

Phase ${opts.phase} ${opts.kr}
Demo: \`${opts.demo}\`

${tableSection}
---
🤖 Auto-generated by \`scripts/post-issue-evidence.ts\` (Phase 58)`;
}

/**
 * 展开 glob 模式并按时刻（数值）排序，返回 ImageEntry 列表。
 * @param pattern  glob 模式，如 docs/regression/phase-50/runner-3d/*.png
 * @param fsImpl   可注入的 fs 实现（测试时传入 mock）
 */
export function parseImagesGlob(pattern: string, fsImpl?: GlobFS): ImageEntry[] {
  const files = fsImpl ? fsImpl.glob(pattern) : syncGlob(pattern);
  return files
    .map(f => ({ moment: path.basename(f, path.extname(f)), filePath: f }))
    .sort((a, b) => parseInt(a.moment) - parseInt(b.moment))
    .map(entry => ({ moment: entry.moment, url: entry.filePath }));
}

// ─────────────────────────────────────────────
// 内部辅助
// ─────────────────────────────────────────────

/** 简单的同步 glob，只支持 dir/*.ext 形式 */
function syncGlob(pattern: string): string[] {
  const lastSlash = pattern.lastIndexOf('/');
  const dir = lastSlash === -1 ? '.' : pattern.slice(0, lastSlash);
  const fileGlob = lastSlash === -1 ? pattern : pattern.slice(lastSlash + 1);

  if (!fsNode.existsSync(dir)) return [];

  const regex = new RegExp(
    '^' + fileGlob.replace(/\./g, '\\.').replace(/\*/g, '.*') + '$',
  );
  return fsNode
    .readdirSync(dir)
    .filter(f => regex.test(f))
    .map(f => [dir, f].join('/'));
}

/** 解析命令行参数 */
function parseCliArgs(argv: string[]): Record<string, string | boolean> {
  const result: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (token === '--dry-run') {
      result['dry-run'] = true;
    } else if (token.startsWith('--')) {
      const key = token.slice(2);
      result[key] = argv[i + 1] ?? '';
      i++;
    }
  }
  return result;
}

// ─────────────────────────────────────────────
// CLI 入口（仅在直接执行时运行）
// ─────────────────────────────────────────────

function main(): void {
  const args = parseCliArgs(process.argv.slice(2));

  const issue = args['issue'] as string | undefined;
  const phase = args['phase'] as string | undefined;
  const kr = args['kr'] as string | undefined;
  const imagesGlob = args['images'] as string | undefined;
  const repo = (args['repo'] as string | undefined) ?? 'MoonKing123/lucid-3d';
  const dryRun = args['dry-run'] === true;

  // 参数校验
  const missing: string[] = [];
  if (!issue) missing.push('--issue');
  if (!phase) missing.push('--phase');
  if (!kr) missing.push('--kr');
  if (!imagesGlob) missing.push('--images');

  if (missing.length > 0) {
    process.stderr.write(`错误：缺少必填参数：${missing.join(', ')}\n`);
    process.stderr.write(
      '用法：tsx scripts/post-issue-evidence.ts --issue <n> --phase <n> --kr <name> --images <glob> [--demo <name>] [--repo <owner/repo>] [--dry-run]\n',
    );
    process.exit(1);
  }

  // 展开 glob
  const rawEntries = parseImagesGlob(imagesGlob as string);
  if (rawEntries.length === 0) {
    process.stderr.write(`错误：glob 模式未匹配到任何文件：${imagesGlob}\n`);
    process.exit(1);
  }

  // 推断 demo 名称（如未指定）
  const demo =
    (args['demo'] as string | undefined) ?? inferDemoFromPath(rawEntries[0].url);

  // 构建 raw URL
  const images: ImageEntry[] = rawEntries.map(entry => ({
    moment: entry.moment,
    url: buildRawUrl(entry.url, repo),
  }));

  // 生成 markdown
  const markdown = generateMarkdown({
    phase: Number(phase),
    kr: kr as string,
    demo,
    images,
  });

  if (dryRun) {
    process.stdout.write(markdown + '\n');
    process.exit(0);
  }

  // 调用 gh api 发布评论
  try {
    const escapedBody = markdown.replace(/'/g, `'\\''`);
    const result = execSync(
      `gh api repos/${repo}/issues/${issue}/comments -f body='${escapedBody}'`,
      { encoding: 'utf8' },
    );
    const json = JSON.parse(result);
    const commentUrl = json.html_url as string;
    process.stdout.write(commentUrl + '\n');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`gh api 调用失败：${msg}\n`);
    process.exit(1);
  }
}

// 判断是否直接执行（而非被 import）
const isMain =
  typeof process !== 'undefined' &&
  process.argv[1] !== undefined &&
  (process.argv[1].endsWith('post-issue-evidence.ts') ||
    process.argv[1].endsWith('post-issue-evidence.js'));

if (isMain) {
  main();
}
