/**
 * scripts/post-phase58-kr4.ts
 * Phase 58 KR4 驱动脚本：批量向 Phase 50-57 共 27 个 KR Issue 贴视觉证据评论。
 *
 * 用法：
 *   tsx scripts/post-phase58-kr4.ts [--dry-run]
 *
 * --dry-run  仅打印将要发布的 markdown，不实际调用 gh api
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import { ISSUE_MAPPING } from './regression-mapping.js';

const REPO = 'MoonKing123/lucid-3d';
// 截图采集日期（KR3 回归运行时间）
const EVIDENCE_DATE = '2026-05-10';
const PHASE_DIR = 'docs/regression/phase-57';
const DRY_RUN = process.argv.includes('--dry-run');

function listPngs(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.png'))
    .sort((a, b) => parseInt(a) - parseInt(b))
    .map(f => path.join(dir, f));
}

function rawUrl(filePath: string): string {
  return `https://raw.githubusercontent.com/${REPO}/main/${filePath.replace(/\\/g, '/')}`;
}

interface Result {
  issue: number;
  ok: boolean;
  url?: string;
  error?: string;
}

const results: Result[] = [];

for (const entry of ISSUE_MAPPING) {
  const dir = `${PHASE_DIR}/${entry.demo}`;
  const files = listPngs(dir);

  const tableRows = files
    .map(f => {
      const moment = path.basename(f, '.png');
      return `| ${moment} | ![${moment}](${rawUrl(f)}) |`;
    })
    .join('\n');

  const tableSection =
    files.length > 0
      ? `截图证据：\n\n| 时刻 | 截图 |\n|------|------|\n${tableRows}\n`
      : `截图证据：\n\n（无截图）\n`;

  const body = `✅ Regression Verified ${EVIDENCE_DATE}

Phase ${entry.phase} ${entry.kr}
Demo: \`${entry.demo}\`

${tableSection}
---
🤖 Auto-generated by \`scripts/post-phase58-kr4.ts\` (Phase 58 KR4)`;

  if (DRY_RUN) {
    console.log(`\n${'='.repeat(60)}`);
    console.log(`Issue #${entry.issue} — Phase ${entry.phase} ${entry.kr}`);
    console.log('='.repeat(60));
    console.log(body);
    continue;
  }

  try {
    const escapedBody = body.replace(/'/g, `'\\''`);
    const result = execSync(
      `gh api repos/${REPO}/issues/${entry.issue}/comments -f body='${escapedBody}'`,
      { encoding: 'utf8' },
    );
    const json = JSON.parse(result) as { html_url: string };
    const url = json.html_url;
    console.log(`#${entry.issue} ✅  ${url}`);
    results.push({ issue: entry.issue, ok: true, url });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`#${entry.issue} ❌  ${msg}`);
    results.push({ issue: entry.issue, ok: false, error: msg });
  }
}

if (!DRY_RUN) {
  const ok = results.filter(r => r.ok).length;
  const fail = results.filter(r => !r.ok).length;
  console.log(`\n完成：${ok} 成功，${fail} 失败`);
  if (fail > 0) process.exit(1);
}
