import { describe, it, expect, vi } from 'vitest';
import { generateMarkdown, parseImagesGlob, inferDemoFromPath, buildRawUrl } from '../../../scripts/post-issue-evidence';

describe('post-issue-evidence', () => {
  describe('generateMarkdown', () => {
    it('produces markdown with 4 image rows', () => {
      const md = generateMarkdown({
        phase: 50,
        kr: 'KR1 ColorLUTPass',
        demo: 'runner-3d',
        date: '2026-05-10',
        images: [
          { moment: '0s', url: 'https://raw.githubusercontent.com/MoonKing123/lucid-3d/main/docs/regression/phase-50/runner-3d/0s.png' },
          { moment: '5s', url: 'https://raw.githubusercontent.com/MoonKing123/lucid-3d/main/docs/regression/phase-50/runner-3d/5s.png' },
          { moment: '15s', url: 'https://raw.githubusercontent.com/MoonKing123/lucid-3d/main/docs/regression/phase-50/runner-3d/15s.png' },
          { moment: '30s', url: 'https://raw.githubusercontent.com/MoonKing123/lucid-3d/main/docs/regression/phase-50/runner-3d/30s.png' },
        ],
      });
      expect(md).toContain('Regression Verified 2026-05-10');
      expect(md).toContain('Phase 50 KR1 ColorLUTPass');
      expect(md).toContain('Demo: `runner-3d`');
      expect(md.match(/!\[/g)?.length).toBe(4); // 4 张图
    });

    it('includes auto-generated footer', () => {
      const md = generateMarkdown({ phase: 50, kr: 'KR1', demo: 'test', images: [] });
      expect(md).toContain('Auto-generated by `scripts/post-issue-evidence.ts`');
    });
  });

  describe('inferDemoFromPath', () => {
    it('extracts demo name from regression path', () => {
      expect(inferDemoFromPath('docs/regression/phase-50/runner-3d/0s.png')).toBe('runner-3d');
      expect(inferDemoFromPath('docs/regression/phase-57/br-12p/30s.png')).toBe('br-12p');
    });

    it('returns "unknown" if path does not match', () => {
      expect(inferDemoFromPath('/tmp/foo.png')).toBe('unknown');
    });
  });

  describe('buildRawUrl', () => {
    it('generates GitHub raw URL', () => {
      expect(buildRawUrl('docs/regression/phase-50/runner-3d/0s.png', 'MoonKing123/lucid-3d'))
        .toBe('https://raw.githubusercontent.com/MoonKing123/lucid-3d/main/docs/regression/phase-50/runner-3d/0s.png');
    });
  });

  describe('parseImagesGlob', () => {
    it('expands glob pattern and sorts by moment', () => {
      const fs = { glob: vi.fn().mockReturnValue([
        'docs/regression/phase-50/runner-3d/30s.png',
        'docs/regression/phase-50/runner-3d/0s.png',
        'docs/regression/phase-50/runner-3d/15s.png',
        'docs/regression/phase-50/runner-3d/5s.png',
      ]) };
      const result = parseImagesGlob('docs/regression/phase-50/runner-3d/*.png', fs);
      expect(result.map(r => r.moment)).toEqual(['0s', '5s', '15s', '30s']);
    });
  });
});
